base_config: configs/pretrain/model-L_small-data.yaml
model:  # PDEformer-2-fast
  inr:
    dim_hidden: 256
data:
  multi_pde:
    # Data can be downloaded using: https://github.com/functoreality/pdefoundry-2/blob/main/download/pdefoundry2_train.sh
    train:
      dcr_base:
        format: dedalus_v5.1_DiffConvecReac2D_hom_cU1_k1e-03_0.01_seed%d
        begin: 2
        num: 110
      dcr_npX:
        format: dedalus_v5.1_DiffConvecReac2D_hom_npX_cU1_k1e-03_0.01_seed%d
        begin: 54
        num: 105
      dcrLgK_npY1:
        format: dedalus_v5.1_DiffConvecReac2D_hom_npY_cU1_k1e-03_0.01_seed%d
        begin: 2
        num: 50
      dcr_npY2:
        format: dedalus_v5.1_DiffConvecReac2D_hom_npY_cU1_k1e-03_0.01_seed%d
        begin: 161
        num: 55
      dcr_disk:
        format: dedalus_v5.1_DiffConvecReac2D_hom_disk_cU1_k1e-03_0.01_seed%d
        begin: 1
        num: 200
      dcr_sJ3:
        format: dedalus_v5.1_DiffConvecReac2D_hom_sJ3_cU1_k1e-03_0.01_seed%d
        begin: 2
        num: 125
      dcr_inhom:
        format: dedalus_v5.1_DiffConvecReac2D_inhom_cU1_k1e-03_0.1_seed%d
        begin: 2
        num: 100
      wave_base:
        format: dedalus_v5.1_Wave2D_hom_sJ3_cU1_k1e-02_4_seed%d
        begin: 2
        num: 125
      wave_npX:
        format: dedalus_v5.1_Wave2D_hom_npX_sJ3_cU1_k1e-02_4_seed%d
        begin: 3
        num: 90
        step: 2
      wave_npY:
        format: dedalus_v5.1_Wave2D_hom_npY_sJ3_cU1_k1e-02_4_seed%d
        begin: 4
        num: 90
        step: 2
      wave_disk:
        format: dedalus_v5.1_Wave2D_hom_disk_cU1_k1e-02_4_seed%d
        begin: 1
        num: 200
      wave_inhom:
        format: dedalus_v5.1_Wave2D_inhom_sJ3_cU1_k1e-02_4_seed%d
        begin: 2
        num: 100
      mvdcr_2:
        format: dedalus_v5.1_MCompn2D_hom_nv2_cU1_k1e-03_0.01_seed%d
        begin: 2
        num: 160
      mvdcr_2_0:  # linear flux case
        format: dedalus_v5.1_MCompn2D_hom_fNL0_nv2_cU1_k1e-03_0.01_seed%d
        begin: 1
        num: 100
      mvdcr_3_1:
        format: dedalus_v5.1_MCompn2D_hom_fNL1_nv3_cU1_k1e-03_0.01_seed%d
        begin: 1
        num: 200
      mvdcr_4_0:
        format: dedalus_v5.1_MCompn2D_hom_fNL0_nv4_cU1_k1e-03_0.01_seed%d
        begin: 1
        num: 200
      dcdcr_icV:
        format: dedalus_v5.1_DivConstrDCR2D_icV_hom_cU1_k1e-03_0.01_seed%d
        begin: 2
        num: 100
      dcdcr_icA:
        format: dedalus_v5.1_DivConstrDCR2D_icA_hom_cU1_k1e-03_0.01_seed%d
        begin: 2
        num: 100
      mvwave_2:
        format: dedalus_v5.1_MCWave2D_hom_nv2_cU1_k1e-02_4_seed%d
        begin: 2
        num: 120
      mvwave_3:
        format: dedalus_v5.1_MCWave2D_hom_nv3_cU1_k1e-02_4_seed%d
        begin: 2
        num: 100
      mvwave_4:
        format: dedalus_v5.1_MCWave2D_hom_nv4_cU1_k1e-02_4_seed%d
        begin: 2
        num: 100
      dcwave_icV:
        format: dedalus_v5.1_DivConstrWave2D_icV_hom_cU1_k1e-02_4_seed%d
        begin: 2
        num: 100
      dcwave_icA:
        format: dedalus_v5.1_DivConstrWave2D_icA_hom_cU1_k1e-02_4_seed%d
        begin: 2
        num: 100
      swe:
        format: dedalus_v5.1_SWE2D_hom_cU1_k1e-03_0.01_seed%d
        begin: 1
        num: 100
      elasticsteady:
        format: fenicsx_v2.1_ElasticSteady2D_iso_cU1_k5e-01_2_nf3_ntf1_ftype1_scatFalse_N128_seed%d
        begin: 1
        num: 255
    # Data can be downloaded using: https://github.com/functoreality/pdefoundry-2/blob/main/download/pdefoundry2_test.sh
    test:
      dcr_base: dedalus_v5.1_DiffConvecReac2D_hom_cU1_k1e-03_0.01_seed1
      dcrLgK_base: dedalus_v5.1_DiffConvecReac2D_hom_cU1_k1e-03_0.01_seed1
      dcr_npX: dedalus_v5.1_DiffConvecReac2D_hom_npX_cU1_k1e-03_0.01_seed53
      dcr_npY: dedalus_v5.1_DiffConvecReac2D_hom_npY_cU1_k1e-03_0.01_seed1
      dcr_disk: dedalus_v5.1_DiffConvecReac2D_hom_disk_cU1_k1e-03_0.01_seed0
      dcr_sJ3: dedalus_v5.1_DiffConvecReac2D_hom_sJ3_cU1_k1e-03_0.01_seed1
      dcr_inhom: dedalus_v5.1_DiffConvecReac2D_inhom_cU1_k1e-03_0.1_seed1
      dcr_inhom_lowK: dedalus_v5.1_DiffConvecReac2D_inhom_cU1_k1e-03_0.01_seed1  # no training set
      wave_base: dedalus_v5.1_Wave2D_hom_sJ3_cU1_k1e-02_4_seed1
      wave_npX: dedalus_v5.1_Wave2D_hom_npX_sJ3_cU1_k1e-02_4_seed1
      wave_npY: dedalus_v5.1_Wave2D_hom_npY_sJ3_cU1_k1e-02_4_seed2
      wave_disk: dedalus_v5.1_Wave2D_hom_disk_cU1_k1e-02_4_seed0
      wave_inhom: dedalus_v5.1_Wave2D_inhom_sJ3_cU1_k1e-02_4_seed1
      mvdcr_2: dedalus_v5.1_MCompn2D_hom_nv2_cU1_k1e-03_0.01_seed1
      mvdcr_2_0: dedalus_v5.1_MCompn2D_hom_fNL0_nv2_cU1_k1e-03_0.01_seed0
      mvdcr_3_0: dedalus_v5.1_MCompn2D_hom_fNL0_nv3_cU1_k1e-03_0.01_seed0  # no training set
      mvdcr_3_1: dedalus_v5.1_MCompn2D_hom_fNL1_nv3_cU1_k1e-03_0.01_seed0
      mvdcr_4_0: dedalus_v5.1_MCompn2D_hom_fNL0_nv4_cU1_k1e-03_0.01_seed0
      mvdcr_5_0: dedalus_v5.1_MCompn2D_hom_fNL0_nv5_cU1_k1e-03_0.01_seed0  # ood
      dcdcr_icV: dedalus_v5.1_DivConstrDCR2D_icV_hom_cU1_k1e-03_0.01_seed1
      dcdcr_icA: dedalus_v5.1_DivConstrDCR2D_icA_hom_cU1_k1e-03_0.01_seed1
      mvwave_2: dedalus_v5.1_MCWave2D_hom_nv2_cU1_k1e-02_4_seed1
      mvwave_3: dedalus_v5.1_MCWave2D_hom_nv3_cU1_k1e-02_4_seed1
      mvwave_4: dedalus_v5.1_MCWave2D_hom_nv4_cU1_k1e-02_4_seed1
      # mvwave_5: dedalus_v5.1_MCWave2D_hom_nv5_cU1_k1e-02_4_seed1  # needs max_n_scalar_nodes=256, max_n_function_nodes=20
      dcwave_icV: dedalus_v5.1_DivConstrWave2D_icV_hom_cU1_k1e-02_4_seed1
      dcwave_icA: dedalus_v5.1_DivConstrWave2D_icA_hom_cU1_k1e-02_4_seed1
      swe: dedalus_v5.1_SWE2D_hom_cU1_k1e-03_0.01_seed0
      elasticsteady: fenicsx_v2.1_ElasticSteady2D_iso_cU1_k5e-01_2_nf3_ntf1_ftype1_scatFalse_N128_seed0
  dynamic:
    enabled: True
    type_default:
      n_logical_dataset: 1
      max_inactive_files: 1
    type_custom:
      - types: [dcr_disk, wave_disk, mvdcr_2, mvdcr_3_1, mvdcr_4_0, dcdcr_icV, dcdcr_icA, dcwave_icV, swe]
        n_logical_dataset: 4
        max_inactive_files: 2
    remove_type: file+dag
    upload_dag: True
train:
  lr_scheduler:
    type: exp
    decay: 0.1
eval:
  dataset_per_type: 0  # run evaluation manually and separately after training is done
record_dir: "exp/pretrain/full-data/model-M"
