base_config: configs/finetune/pdebench-swe-rdb_model-M.yaml
model:
  load_ckpt: path/to/your/downloaded/model-M.ckpt  # set to "none" for from-scratch
data:
  num_samples_per_file:
    train: 240
  pde_dag:
    max_n_scalar_nodes: 128
    max_n_function_nodes: 8
  single_pde:
    param_name: ins_coupled_fname  # {ins_coupled_fname (regular), ins_c_convec (equivalent), ins_c_incomplete, ins_c_unknown, ins_c_wrong}
    train: [dedalus_v5.1_Baseline2D_INSTracer_icA_noP_db1_nu0.001D0.01_seed0]
train:
  total_batch_size: 80
  lr_init: 1.e-4
  epochs: 1000
  lr_scheduler:
    type: cos
    enable_warmup: True
    warmup_epochs: 10
eval:
  total_batch_size: 24
  interval: 50
  plot_num_per_type: 0
record_dir: exp/benchmark_data/ins-tracer/train-240/model-M/regular
