# train with 8 NPUs
model_type: cnn_deeponet  # {pdeformer, deeponet, cnn_deeponet, unet2d, fno2d, fno3d}
deeponet:  # applies to {deeponet, cnn_deeponet}
  trunk_dim_hidden: 256
  trunk_num_layers: 6
  branch_dim_hidden: 256
  branch_num_layers: 6
  dim_out: 2048
  num_pos_enc: 0  # 0 means no position encoding
data:
  path: ../data_download  # or any path/to/your/data_download
  type: single_pde
  num_workers: 8
  num_samples_per_file:
    train: 900
    test: 100
  pde_dag:
    max_n_scalar_nodes: 128
    max_n_function_nodes: 8
    disconn_attn_bias: -inf
  single_pde:
    param_name: ins_coupled_fname
    # Data can be downloaded at: data-download.obs.cn-northeast-227.dlaicc.com/dedalus_v5.1/Baseline2D/dedalus_v5.1_Baseline2D_INSTracer_icA_noP_db1_nu0.001D0.01_seed0.hdf5
    train: [dedalus_v5.1_Baseline2D_INSTracer_icA_noP_db1_nu0.001D0.01_seed0]
train:
  total_batch_size: 40
  num_txyz_samp_pts: 8192
  lr_init: 1.e-4
  epochs: 1000
  loss:
    type: RMSE
    normalize: True
    normalize_eps: 0.05
  optimizer: Adam
  weight_decay: 0.0
  lr_scheduler:
    type: cos
    enable_warmup: True
    warmup_epochs: 10
  grad_clip_value: 1  # -1 means no gradient clipping
eval:
  total_batch_size: 8
  interval: 50
  plot_num_per_type: 0
record_dir: exp/benchmark_data/ins_tracer/train-900/cnn_deeponet
